name: Terraform Apply PROD

on:
  push:
    branches:
      - main
      - prod

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: aws-prod   # usa o Environment que você configurou

    permissions:
      contents: read
      id-token: write       # necessário para OIDC

    steps:
      # Pega o código
      - name: Checkout
        uses: actions/checkout@v4

      # Configura Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Assume a role via OIDC
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      # Terraform Init
      - name: Terraform Init
        working-directory: terraform/stacks/security/github-oidc-prod
        run: terraform init -input=false

      # Terraform Plan
      - name: Terraform Plan
        working-directory: terraform/stacks/security/github-oidc-prod
        run: terraform plan -input=false

      # Terraform Apply
      - name: Terraform Apply
        working-directory: terraform/stacks/security/github-oidc-prod
        run: terraform apply -auto-approve

