name: Terraform Plan

on:
  pull_request:
    branches: [ "main", "prod" ]
    paths:
      - "terraform/**"   # só roda se arquivos Terraform mudarem

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write    # necessário para OIDC

    steps:
      # Checkout do código
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Assume a role via OIDC
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      # Terraform Init
      - name: Terraform Init
        working-directory: terraform/stacks/security/github-oidc-prod
        run: terraform init -input=false

      # Terraform Format check
      - name: Terraform Format
        working-directory: terraform/stacks/security/github-oidc-prod
        run: terraform fmt -check -recursive

      #  Terraform Validate
      - name: Terraform Validate
        working-directory: terraform/stacks/security/github-oidc-prod
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        working-directory: terraform/stacks/security/github-oidc-prod
        id: plan
        run: terraform plan -input=false -no-color

